---
- hosts: local
  gather_facts: True
  remote_user: root
  become: yes
  become_method: sudo
  connection: local
  roles:
    - { role: akamai_purge, akamai_user: "{{akamai_credentials.username}}", akamai_password: "{{akamai_credentials.password}}" }
