---


- hosts: local
  gather_facts: False
  connection: psrp
  sudo: no
  roles:
    - { role: akamai_purge, akamai_user: "{{akamai_credentials.username}}", akamai_password: "{{akamai_credentials.password}}" }
